/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memebot;

import static com.sun.webkit.network.URLs.newURL;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.SocketException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Basil Nikolopoulos <nikolopoulosbasil.com>
 */
public class getLyrics {

    private static String[] links = {"https://www.azlyrics.com/lyrics/snoopdogg/bathtub.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gfunkintro.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ginandjuice.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thashiznit.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lodidodiintro.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lodidodi.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/murderwasthecasedeathaftervisualizingeternity.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/serialkilla.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whoamiwhatsmyname.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/forallmyniggazbitches.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/aintnofunifthehomiescanthavenone.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/chronicbreak.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/doggydoggworld.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/youbettaasksomebodygzandhustlasintro.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gzandhustlas.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ubettarecognizepumppumpintro.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/pumppump.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thadoggfather.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/upjumpthaboogie.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/freestyleconversation.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/snoopbounce.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/goldrush.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/tearemoffmemydoggz.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/youthought.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/vapors.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/groupie.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/2001.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sixxminutes.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ojwakeup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/snoopsupsideyourhead.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/blueberry.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/doggyland.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/downtownassassins.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/slowdown.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/woof.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ginjuice2.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/hustleball.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dontletgo.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/trutankdogs.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whatchagondo.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/stillagthang.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/20dollarstomyname.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dogsgetlonely2.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/aintnutinpersonal.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dpgangsta.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gameoflife.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/seeyawhenigetthere.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/payinforpussy.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/picturethis.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/doggzgonnagetya.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/hoesmoneyandclout.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/getboutitrowdy.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/buckem.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/trustme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/myheatgoesboom.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/snoopafella.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/inlovewithathug.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gbedtimestories.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/down4myniggas.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bettadays.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/somethinboutyobidness.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bitchplease.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dointoomuch.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gangstaride.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ghettosymphony.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/partywithadpg.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bussnrocks.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/justdippin.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/donttell.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/20minutes.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ilovemymomma.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/henneseyandbuddah.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/snoopdogg.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/truelies.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/wrongidea.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/goaway.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/setitoff.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/staceyadams.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/laylow.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bringiton.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gamecourt.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/issues.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/brakefluidbitchespumpyobrakes.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ready2ryde.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/loosencontrol.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/icantswim.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/leavemealone.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/backupoffme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/yallgonemissme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/iluvit.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/eastsideridaz.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/criphop.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/friends.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/nowisthetime.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/cool14471.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dogghouseinyourmouth.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/connected.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/macbiblechapter211verse2021.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/breakabitchtilidie.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/stickyfingers.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/latenight.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/solow.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/stoplight.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/fromthachuuuchtodapalace.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ibelieveinyou.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lollipop.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ballin.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/beautiful.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/paperdup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/wasntyourfault.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/boplaya.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/hourglass.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/theoneandonly.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/imissthatbitch.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/fromlongbeach2brickcity.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/suitednbooted.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/yougotwhatiwant.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/batmanrobin.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/pimpslappd.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/missioncleopatra.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/introilovetogiveyoulight.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bangout.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dropitlikeitshot.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/canigetafliccwitchu.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/upsdowns.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thebidness.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/snoopdodoubleg.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letsgetblown.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/stepyogameup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/perfect.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/freshpairofpantieson.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/promisei.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ohno.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/canucontrolyohoe.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/signs.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/imthrewwitchu.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/passitpassit.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/girllikeu.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/intrology.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thinkaboutit.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/crazy.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/vato.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thatsthat.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/candydrippinlikewater.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/getalight.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gangbangn101.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bosslife.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lax.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/10lilgrips.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/roundhere.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/abitchiknew.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/likethis.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whichoneofyou.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/iwannafuckyou.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/psst.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/beatuponyopads.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dontstop.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/imagine.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/conversations.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/awordwitchyaintro.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/pressplay.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sdisout.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gangstalikeme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/nevahave2worry.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sexualeruption.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lifeofdaparty.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/wasteoftime.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/cool68976.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/setsup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/deezhollywoodnights.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whatevaudo.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/staxxxinmyjeans.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/beenaroundthaworld.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letitout.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/mymedicine.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ridininmychevy.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thosegurlz.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/onechancemakeitgood.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whydidyouleaveme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/cantsaygoodbye.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/doggystyle.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/intro.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/iwannarock.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/2minutewarning.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/1800.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/differentlanguages.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gangstaluv.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/pronto.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thatsthahomie.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/upsidedown.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/secrets.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/pimpinaintez.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/luvdrunk.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/special.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/iwannarockthekingsgmix.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/protocol.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sogangsta.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/houseshoes.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thattree.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/youregonnaluvme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/prontogmix.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gangstaluv.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/toyzndahood.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thewaylifeusedtobe.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/myownway.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/wonderwhatitdo.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/myfuckinhouse.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/peerpressure.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/idontneednobitch.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/platinum.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/boom.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/werestncali.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ellay.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gangbangrookie.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thisweedizmine.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/wet.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/takeuhome.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sumthinglikethisnight.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/superman.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/eyezclosed.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/raisedindahood.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/itsdonlything.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/coldgame.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sweatdavidguettaremix.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/smokinon.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/igetlifted.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/youcanputitinazagimmaputitinablunt.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/630.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/talentshow.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letsgostudy.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/youngwildfree.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/og.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/frenchinhale.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/itcouldbeeasy.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/worldclass.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thatgood.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/highschool.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/devssong.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/rebelway.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/herecomestheking.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lightersup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/solong.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/getaway.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/nogunsallowed.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/fruitjuice.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/smoketheweed.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/tiredofrunning.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thegoodgood.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/tornapart.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ashtraysheartbreaks.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/boulevard.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/remedy.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lalala.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/hardertimes.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/introthadogginme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bad4me.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letthekspray.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/takeyourtime.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/faddin.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/allmyhoes.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/balltilweball.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/passengerseat.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/becauseimblack.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letmeexplain.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whatsthedifference.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/groovethang.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/hitdapavement.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letitgo.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/fadenaway.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/1question.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/domythang.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/illbethere4u.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/highwitme.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/poppopbang.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/happybirthday.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dickwalk.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/fullofthatshit.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/neverhaditlikethis.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/phenomeon.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/onedge.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/talkinloud.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/weednwax.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/cadillacs.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/aroundtheworld.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/misseverythang.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whatsyopleasure.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/aintnobody.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/terradectacal.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/aintitman.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/feellikeheaven.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/freestyle.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/happybirthdaypt2.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gangstasdontlivethatlong.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/californiaroll.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/thiscity.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ruafreak.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/awake.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/somanypros.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/peachesncream.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/edibles.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/iknewthat.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/runaway.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/imyadogg.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/legend.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/tentoesdown.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/dontstop492095.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/supercrip.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/coolaidman.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letmeseeemup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/pointseenmoneygone.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/ohnana.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/mycarz.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/twoormore.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/affiliated.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/feelaboutsnoop.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lightitup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sidepiece.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/kushups.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/doubletap.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/gotthose.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letthebeatdropcelebrate.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/whatif.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/revolution.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/nevaleft.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/momentifeared.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/baccindadayz.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/promiseyouthis.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/trashbags.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/swivel.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/goon.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/bigmouth.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/tossit.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/420blazeup.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lavendernightfallremix.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/letusbegin.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/mountkushmore.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/vaporsdjbattlecatremix.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/stillhere.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/lovearoundtheworld.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/maca.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/3scompany.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/goodfoot.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/disfinnabeabreeze.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/noneofmine.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/mylastname.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sportscenter.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/flyaway.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/intro615372.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/everything.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/220.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/waves.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/idontcare.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/doggytails.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/motivation.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/onthedouble.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/saved.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/sunshinefeelgood.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/you.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/onemoreday.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/blessingmeagain.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/blessedhighlyfavoredremix.html",
        "https://www.azlyrics.com/lyrics/snoopdogg/wordsarefew.html","https://www.azlyrics.com/lyrics/metallica/hitthelights.html",
"https://www.azlyrics.com/lyrics/metallica/thefourhorsemen.html",
"https://www.azlyrics.com/lyrics/metallica/motorbreath.html",
"https://www.azlyrics.com/lyrics/metallica/jumpinthefire.html",
"https://www.azlyrics.com/lyrics/metallica/whiplash.html",
"https://www.azlyrics.com/lyrics/metallica/phantomlord.html",
"https://www.azlyrics.com/lyrics/metallica/noremorse.html",
"https://www.azlyrics.com/lyrics/metallica/seekdestroy.html",
"https://www.azlyrics.com/lyrics/metallica/metalmilitia.html",

"https://www.azlyrics.com/lyrics/metallica/fightfirewithfire.html",
"https://www.azlyrics.com/lyrics/metallica/ridethelightning.html",
"https://www.azlyrics.com/lyrics/metallica/forwhomthebelltolls.html",
"https://www.azlyrics.com/lyrics/metallica/fadetoblack.html",
"https://www.azlyrics.com/lyrics/metallica/trappedunderice.html",
"https://www.azlyrics.com/lyrics/metallica/escape.html",
"https://www.azlyrics.com/lyrics/metallica/creepingdeath.html",

"https://www.azlyrics.com/lyrics/metallica/battery.html",
"https://www.azlyrics.com/lyrics/metallica/masterofpuppets.html",
"https://www.azlyrics.com/lyrics/metallica/thethingthatshouldnotbe.html",
"https://www.azlyrics.com/lyrics/metallica/welcomehomesanitarium.html",
"https://www.azlyrics.com/lyrics/metallica/disposableheroes.html",
"https://www.azlyrics.com/lyrics/metallica/lepermessiah.html",
"https://www.azlyrics.com/lyrics/metallica/damageinc.html",

"https://www.azlyrics.com/lyrics/metallica/helpless.html",
"https://www.azlyrics.com/lyrics/metallica/thesmallhours.html",
"https://www.azlyrics.com/lyrics/metallica/thewait.html",
"https://www.azlyrics.com/lyrics/metallica/crashcourseinbrainsurgery.html",
"https://www.azlyrics.com/lyrics/metallica/lastcaressgreenhell.html",

"https://www.azlyrics.com/lyrics/metallica/blackened.html",
"https://www.azlyrics.com/lyrics/metallica/andjusticeforall.html",
"https://www.azlyrics.com/lyrics/metallica/eyeofthebeholder.html",
"https://www.azlyrics.com/lyrics/metallica/one.html",
"https://www.azlyrics.com/lyrics/metallica/theshorteststraw.html",
"https://www.azlyrics.com/lyrics/metallica/harvesterofsorrow.html",
"https://www.azlyrics.com/lyrics/metallica/thefrayedendsofsanity.html",
"https://www.azlyrics.com/lyrics/metallica/toliveistodie.html",
"https://www.azlyrics.com/lyrics/metallica/dyerseve.html",

"https://www.azlyrics.com/lyrics/metallica/entersandman.html",
"https://www.azlyrics.com/lyrics/metallica/sadbuttrue.html",
"https://www.azlyrics.com/lyrics/metallica/holierthanthou.html",
"https://www.azlyrics.com/lyrics/metallica/theunforgiven.html",
"https://www.azlyrics.com/lyrics/metallica/whereverimayroam.html",
"https://www.azlyrics.com/lyrics/metallica/donttreadonme.html",
"https://www.azlyrics.com/lyrics/metallica/throughthenever.html",
"https://www.azlyrics.com/lyrics/metallica/nothingelsematters.html",
"https://www.azlyrics.com/lyrics/metallica/ofwolfandman.html",
"https://www.azlyrics.com/lyrics/metallica/thegodthatfailed.html",
"https://www.azlyrics.com/lyrics/metallica/myfriendofmisery.html",
"https://www.azlyrics.com/lyrics/metallica/thestrugglewithin.html",

"https://www.azlyrics.com/lyrics/metallica/aintmybitch.html",
"https://www.azlyrics.com/lyrics/metallica/2x4.html",
"https://www.azlyrics.com/lyrics/metallica/thehousejackbuilt.html",
"https://www.azlyrics.com/lyrics/metallica/untilitsleeps.html",
"https://www.azlyrics.com/lyrics/metallica/kingnothing.html",
"https://www.azlyrics.com/lyrics/metallica/herooftheday.html",
"https://www.azlyrics.com/lyrics/metallica/bleedingme.html",
"https://www.azlyrics.com/lyrics/metallica/cure.html",
"https://www.azlyrics.com/lyrics/metallica/poortwistedme.html",
"https://www.azlyrics.com/lyrics/metallica/wastingmyhate.html",
"https://www.azlyrics.com/lyrics/metallica/mamasaid.html",
"https://www.azlyrics.com/lyrics/metallica/thornwithin.html",
"https://www.azlyrics.com/lyrics/metallica/ronnie.html",
"https://www.azlyrics.com/lyrics/metallica/theoutlawtorn.html",

"https://www.azlyrics.com/lyrics/metallica/fuel.html",
"https://www.azlyrics.com/lyrics/metallica/thememoryremains.html",
"https://www.azlyrics.com/lyrics/metallica/devilsdance.html",
"https://www.azlyrics.com/lyrics/metallica/theunforgivenii.html",
"https://www.azlyrics.com/lyrics/metallica/betterthanyou.html",
"https://www.azlyrics.com/lyrics/metallica/slither.html",
"https://www.azlyrics.com/lyrics/metallica/carpediembaby.html",
"https://www.azlyrics.com/lyrics/metallica/badseed.html",
"https://www.azlyrics.com/lyrics/metallica/wherethewildthingsare.html",
"https://www.azlyrics.com/lyrics/metallica/princecharming.html",
"https://www.azlyrics.com/lyrics/metallica/lowmanslyric.html",
"https://www.azlyrics.com/lyrics/metallica/attitude.html",
"https://www.azlyrics.com/lyrics/metallica/fixxxer.html",

"https://www.azlyrics.com/lyrics/metallica/freespeechforthedumb.html",
"https://www.azlyrics.com/lyrics/metallica/itselectric.html",
"https://www.azlyrics.com/lyrics/metallica/sabbracadabra.html",
"https://www.azlyrics.com/lyrics/metallica/turnthepage.html",
"https://www.azlyrics.com/lyrics/metallica/diediemydarling.html",
"https://www.azlyrics.com/lyrics/metallica/loverman.html",
"https://www.azlyrics.com/lyrics/metallica/mercyfulfate.html",
"https://www.azlyrics.com/lyrics/metallica/astronomy.html",
"https://www.azlyrics.com/lyrics/metallica/whiskeyinthejar.html",
"https://www.azlyrics.com/lyrics/metallica/tuesdaysgone.html",
"https://www.azlyrics.com/lyrics/metallica/themoreisee.html",
"https://www.azlyrics.com/lyrics/metallica/helpless.html",
"https://www.azlyrics.com/lyrics/metallica/thesmallhours.html",
"https://www.azlyrics.com/lyrics/metallica/thewait.html",
"https://www.azlyrics.com/lyrics/metallica/crashcourseinbrainsurgery.html",
"https://www.azlyrics.com/lyrics/metallica/lastcaressgreenhell.html",
"https://www.azlyrics.com/lyrics/metallica/amievil.html",
"https://www.azlyrics.com/lyrics/metallica/blitzkrieg.html",
"https://www.azlyrics.com/lyrics/metallica/breadfan.html",
"https://www.azlyrics.com/lyrics/metallica/theprince.html",
"https://www.azlyrics.com/lyrics/metallica/stonecoldcrazy.html",
"https://www.azlyrics.com/lyrics/metallica/sowhat.html",
"https://www.azlyrics.com/lyrics/metallica/killingtime.html",
"https://www.azlyrics.com/lyrics/metallica/overkill.html",
"https://www.azlyrics.com/lyrics/metallica/damagecase.html",
"https://www.azlyrics.com/lyrics/metallica/stonedeadforever.html",
"https://www.azlyrics.com/lyrics/metallica/toolatetoolate.html",

"https://www.azlyrics.com/lyrics/metallica/frantic.html",
"https://www.azlyrics.com/lyrics/metallica/stanger.html",
"https://www.azlyrics.com/lyrics/metallica/somekindofmonster.html",
"https://www.azlyrics.com/lyrics/metallica/dirtywindow.html",
"https://www.azlyrics.com/lyrics/metallica/invisiblekid.html",
"https://www.azlyrics.com/lyrics/metallica/myworld.html",
"https://www.azlyrics.com/lyrics/metallica/shootmeagain.html",
"https://www.azlyrics.com/lyrics/metallica/sweetamber.html",
"https://www.azlyrics.com/lyrics/metallica/unnamedfeeling.html",
"https://www.azlyrics.com/lyrics/metallica/purify.html",
"https://www.azlyrics.com/lyrics/metallica/allwithinmyhands.html",

"https://www.azlyrics.com/lyrics/metallica/thatwasjustyourlife.html",
"https://www.azlyrics.com/lyrics/metallica/theendoftheline.html",
"https://www.azlyrics.com/lyrics/metallica/brokenbeatscarred.html",
"https://www.azlyrics.com/lyrics/metallica/thedaythatnevercomes.html",
"https://www.azlyrics.com/lyrics/metallica/allnightmarelong.html",
"https://www.azlyrics.com/lyrics/metallica/cyanide.html",
"https://www.azlyrics.com/lyrics/metallica/theunforgiveniii.html",
"https://www.azlyrics.com/lyrics/metallica/thejudaskiss.html",
"https://www.azlyrics.com/lyrics/metallica/myapocalypse.html",

"https://www.azlyrics.com/lyrics/metallica/brandenburggate.html",
"https://www.azlyrics.com/lyrics/metallica/theview.html",
"https://www.azlyrics.com/lyrics/metallica/pumpingblood.html",
"https://www.azlyrics.com/lyrics/metallica/mistressdread.html",
"https://www.azlyrics.com/lyrics/metallica/icedhoney.html",
"https://www.azlyrics.com/lyrics/metallica/cheatonme.html",
"https://www.azlyrics.com/lyrics/metallica/frustration.html",
"https://www.azlyrics.com/lyrics/metallica/littledog.html",
"https://www.azlyrics.com/lyrics/metallica/dragon.html",
"https://www.azlyrics.com/lyrics/metallica/juniordad.html",


"https://www.azlyrics.com/lyrics/metallica/hatetrain.html",
"https://www.azlyrics.com/lyrics/metallica/justabulletaway.html",
"https://www.azlyrics.com/lyrics/metallica/hellandback.html",
"https://www.azlyrics.com/lyrics/metallica/rebelofbabylon.html",


"https://www.azlyrics.com/lyrics/metallica/hardwired.html",
"https://www.azlyrics.com/lyrics/metallica/atlasrise.html",
"https://www.azlyrics.com/lyrics/metallica/nowthatweredead.html",
"https://www.azlyrics.com/lyrics/metallica/mothintoflame.html",
"https://www.azlyrics.com/lyrics/metallica/dreamnomore.html",
"https://www.azlyrics.com/lyrics/metallica/haloonfire.html",
"https://www.azlyrics.com/lyrics/metallica/confusion.html",
"https://www.azlyrics.com/lyrics/metallica/manunkind.html",
"https://www.azlyrics.com/lyrics/metallica/herecomesrevenge.html",
"https://www.azlyrics.com/lyrics/metallica/amisavage.html",
"https://www.azlyrics.com/lyrics/metallica/murderone.html",
"https://www.azlyrics.com/lyrics/metallica/spitoutthebone.html",

"https://www.azlyrics.com/lyrics/megadeth/lastriteslovedtodeth.html",
"https://www.azlyrics.com/lyrics/megadeth/killingismybusinessandbusinessisgood.html",
"https://www.azlyrics.com/lyrics/megadeth/theskullbeneaththeskin.html",
"https://www.azlyrics.com/lyrics/megadeth/theboots.html",
"https://www.azlyrics.com/lyrics/megadeth/rattlehead.html",
"https://www.azlyrics.com/lyrics/megadeth/chosenones.html",
"https://www.azlyrics.com/lyrics/megadeth/lookingdownthecross.html",
"https://www.azlyrics.com/lyrics/megadeth/mechanix.html",

"https://www.azlyrics.com/lyrics/megadeth/wakeupdead.html",
"https://www.azlyrics.com/lyrics/megadeth/theconjuring.html",
"https://www.azlyrics.com/lyrics/megadeth/peacesells.html",
"https://www.azlyrics.com/lyrics/megadeth/devilsisland.html",
"https://www.azlyrics.com/lyrics/megadeth/goodmourningblackfriday.html",
"https://www.azlyrics.com/lyrics/megadeth/badomen.html",
"https://www.azlyrics.com/lyrics/megadeth/iaintsuperstitious.html",
"https://www.azlyrics.com/lyrics/megadeth/mylastwords.html",

"https://www.azlyrics.com/lyrics/megadeth/settheworldafire.html",
"https://www.azlyrics.com/lyrics/megadeth/anarchyintheuk.html",
"https://www.azlyrics.com/lyrics/megadeth/maryjane.html",
"https://www.azlyrics.com/lyrics/megadeth/502.html",
"https://www.azlyrics.com/lyrics/megadeth/inmydarkesthour.html",
"https://www.azlyrics.com/lyrics/megadeth/liar.html",
"https://www.azlyrics.com/lyrics/megadeth/hookinmouth.html",

"https://www.azlyrics.com/lyrics/megadeth/holywarsthepunishmentdue.html",
"https://www.azlyrics.com/lyrics/megadeth/hangar18.html",
"https://www.azlyrics.com/lyrics/megadeth/takenoprisoners.html",
"https://www.azlyrics.com/lyrics/megadeth/fivemagics.html",
"https://www.azlyrics.com/lyrics/megadeth/poisonwasthecure.html",
"https://www.azlyrics.com/lyrics/megadeth/lucretia.html",
"https://www.azlyrics.com/lyrics/megadeth/tornadoofsouls.html",
"https://www.azlyrics.com/lyrics/megadeth/dawnpatrol.html",
"https://www.azlyrics.com/lyrics/megadeth/rustinpeacepolaris.html",
"https://www.azlyrics.com/lyrics/megadeth/mycreation.html",

"https://www.azlyrics.com/lyrics/megadeth/skinomyteeth.html",
"https://www.azlyrics.com/lyrics/megadeth/symphonyofdestruction.html",
"https://www.azlyrics.com/lyrics/megadeth/architectureofaggression.html",
"https://www.azlyrics.com/lyrics/megadeth/foreclosureofadream.html",
"https://www.azlyrics.com/lyrics/megadeth/sweatingbullets.html",
"https://www.azlyrics.com/lyrics/megadeth/thiswasmylife.html",
"https://www.azlyrics.com/lyrics/megadeth/countdowntoextinction.html",
"https://www.azlyrics.com/lyrics/megadeth/highspeeddirt.html",
"https://www.azlyrics.com/lyrics/megadeth/psychotron.html",
"https://www.azlyrics.com/lyrics/megadeth/captivehonour.html",
"https://www.azlyrics.com/lyrics/megadeth/ashesinyourmouth.html",

"https://www.azlyrics.com/lyrics/megadeth/reckoningday.html",
"https://www.azlyrics.com/lyrics/megadeth/trainofconsequences.html",
"https://www.azlyrics.com/lyrics/megadeth/addictedtochaos.html",
"https://www.azlyrics.com/lyrics/megadeth/toutlemonde.html",
"https://www.azlyrics.com/lyrics/megadeth/elysianfields.html",
"https://www.azlyrics.com/lyrics/megadeth/thekillingroad.html",
"https://www.azlyrics.com/lyrics/megadeth/bloodofheroes.html",
"https://www.azlyrics.com/lyrics/megadeth/familytree.html",
"https://www.azlyrics.com/lyrics/megadeth/youthanasia.html",
"https://www.azlyrics.com/lyrics/megadeth/ithoughtiknewitall.html",
"https://www.azlyrics.com/lyrics/megadeth/blackcurtains.html",
"https://www.azlyrics.com/lyrics/megadeth/victory.html",

"https://www.azlyrics.com/lyrics/megadeth/trainofconsequences.html",
"https://www.azlyrics.com/lyrics/megadeth/crownofworms.html",
"https://www.azlyrics.com/lyrics/megadeth/blackcurtains.html",
"https://www.azlyrics.com/lyrics/megadeth/ashesinyourmouthlive.html",
"https://www.azlyrics.com/lyrics/megadeth/peacesellslive.html",
"https://www.azlyrics.com/lyrics/megadeth/anarchyintheuklive.html",

"https://www.azlyrics.com/lyrics/megadeth/nomoremrniceguy.html",
"https://www.azlyrics.com/lyrics/megadeth/breakpoint.html",
"https://www.azlyrics.com/lyrics/megadeth/gotohell.html",
"https://www.azlyrics.com/lyrics/megadeth/angryagain.html",
"https://www.azlyrics.com/lyrics/megadeth/99waystodie.html",
"https://www.azlyrics.com/lyrics/megadeth/paranoid.html",
"https://www.azlyrics.com/lyrics/megadeth/diadems.html",
"https://www.azlyrics.com/lyrics/megadeth/problems.html",

"https://www.azlyrics.com/lyrics/megadeth/trust.html",
"https://www.azlyrics.com/lyrics/megadeth/almosthonest.html",
"https://www.azlyrics.com/lyrics/megadeth/usetheman.html",
"https://www.azlyrics.com/lyrics/megadeth/mastermind.html",
"https://www.azlyrics.com/lyrics/megadeth/thedisintegrators.html",
"https://www.azlyrics.com/lyrics/megadeth/illgeteven.html",
"https://www.azlyrics.com/lyrics/megadeth/sin.html",
"https://www.azlyrics.com/lyrics/megadeth/asecretplace.html",
"https://www.azlyrics.com/lyrics/megadeth/havecoolwilltravel.html",
"https://www.azlyrics.com/lyrics/megadeth/shewolf.html",
"https://www.azlyrics.com/lyrics/megadeth/vortex.html",
"https://www.azlyrics.com/lyrics/megadeth/fff.html",
"https://www.azlyrics.com/lyrics/megadeth/trustspanishversion.html",
"https://www.azlyrics.com/lyrics/megadeth/evilthatswithin.html",
"https://www.azlyrics.com/lyrics/megadeth/vortexalternateversion.html",

"https://www.azlyrics.com/lyrics/megadeth/insomnia.html",
"https://www.azlyrics.com/lyrics/megadeth/princeofdarkness.html",
"https://www.azlyrics.com/lyrics/megadeth/enterthearena.html",
"https://www.azlyrics.com/lyrics/megadeth/crushem.html",
"https://www.azlyrics.com/lyrics/megadeth/breadline.html",
"https://www.azlyrics.com/lyrics/megadeth/thedoctoriscalling.html",
"https://www.azlyrics.com/lyrics/megadeth/illbethere.html",
"https://www.azlyrics.com/lyrics/megadeth/wanderlust.html",
"https://www.azlyrics.com/lyrics/megadeth/ecstasy.html",
"https://www.azlyrics.com/lyrics/megadeth/seven.html",
"https://www.azlyrics.com/lyrics/megadeth/timethebeginning.html",
"https://www.azlyrics.com/lyrics/megadeth/timetheend.html",

"https://www.azlyrics.com/lyrics/megadeth/disconnect.html",
"https://www.azlyrics.com/lyrics/megadeth/theworldneedsahero.html",
"https://www.azlyrics.com/lyrics/megadeth/motopsycho.html",
"https://www.azlyrics.com/lyrics/megadeth/1000timesgoodbye.html",
"https://www.azlyrics.com/lyrics/megadeth/burningbridges.html",
"https://www.azlyrics.com/lyrics/megadeth/promises.html",
"https://www.azlyrics.com/lyrics/megadeth/recipeforhatewarhorse.html",
"https://www.azlyrics.com/lyrics/megadeth/losingmysenses.html",
"https://www.azlyrics.com/lyrics/megadeth/dreadandthefugitivemind.html",
"https://www.azlyrics.com/lyrics/megadeth/returntohangar.html",
"https://www.azlyrics.com/lyrics/megadeth/when.html",

"https://www.azlyrics.com/lyrics/megadeth/blackmailtheuniverse.html",
"https://www.azlyrics.com/lyrics/megadeth/diedeadenough.html",
"https://www.azlyrics.com/lyrics/megadeth/kickthechair.html",
"https://www.azlyrics.com/lyrics/megadeth/thescorpion.html",
"https://www.azlyrics.com/lyrics/megadeth/tearsinavial.html",
"https://www.azlyrics.com/lyrics/megadeth/iknowjack.html",
"https://www.azlyrics.com/lyrics/megadeth/backintheday.html",
"https://www.azlyrics.com/lyrics/megadeth/somethingthatimnot.html",
"https://www.azlyrics.com/lyrics/megadeth/truthbetold.html",
"https://www.azlyrics.com/lyrics/megadeth/ofmiceandmen.html",
"https://www.azlyrics.com/lyrics/megadeth/shadowofdeth.html",
"https://www.azlyrics.com/lyrics/megadeth/mykingdomcome.html",

"https://www.azlyrics.com/lyrics/megadeth/sleepwalker.html",
"https://www.azlyrics.com/lyrics/megadeth/washingtonisnext.html",
"https://www.azlyrics.com/lyrics/megadeth/neverwalkalone.html",
"https://www.azlyrics.com/lyrics/megadeth/unitedabominations.html",
"https://www.azlyrics.com/lyrics/megadeth/gearsofwar.html",
"https://www.azlyrics.com/lyrics/megadeth/blessedarethedead.html",
"https://www.azlyrics.com/lyrics/megadeth/playforblood.html",
"https://www.azlyrics.com/lyrics/megadeth/atoutlemondesetmefree.html",
"https://www.azlyrics.com/lyrics/megadeth/amerikhastan.html",
"https://www.azlyrics.com/lyrics/megadeth/youredead.html",
"https://www.azlyrics.com/lyrics/megadeth/burntice.html",

"https://www.azlyrics.com/lyrics/megadeth/thisdaywefight.html",
"https://www.azlyrics.com/lyrics/megadeth/44minutes.html",
"https://www.azlyrics.com/lyrics/megadeth/1320.html",
"https://www.azlyrics.com/lyrics/megadeth/bitethehandthatfeeds.html",
"https://www.azlyrics.com/lyrics/megadeth/bodiesleftbehind.html",
"https://www.azlyrics.com/lyrics/megadeth/endgame.html",
"https://www.azlyrics.com/lyrics/megadeth/thehardestpartoflettinggosealedwithakiss.html",
"https://www.azlyrics.com/lyrics/megadeth/headcrusher.html",
"https://www.azlyrics.com/lyrics/megadeth/howthestoryends.html",
"https://www.azlyrics.com/lyrics/megadeth/therighttogoinsane.html",

"https://www.azlyrics.com/lyrics/megadeth/suddendeath.html",
"https://www.azlyrics.com/lyrics/megadeth/publicenemyno1.html",
"https://www.azlyrics.com/lyrics/megadeth/whoselifeisitanyways.html",
"https://www.azlyrics.com/lyrics/megadeth/wethepeople.html",
"https://www.azlyrics.com/lyrics/megadeth/gunsdrugsmoney.html",
"https://www.azlyrics.com/lyrics/megadeth/neverdead.html",
"https://www.azlyrics.com/lyrics/megadeth/newworldorder.html",
"https://www.azlyrics.com/lyrics/megadeth/fastlane.html",
"https://www.azlyrics.com/lyrics/megadeth/blackswan.html",
"https://www.azlyrics.com/lyrics/megadeth/wrecker.html",
"https://www.azlyrics.com/lyrics/megadeth/millenniumoftheblind.html",
"https://www.azlyrics.com/lyrics/megadeth/deadlynightshade.html",
"https://www.azlyrics.com/lyrics/megadeth/13.html",

"https://www.azlyrics.com/lyrics/megadeth/kingmaker.html",
"https://www.azlyrics.com/lyrics/megadeth/supercollider.html",
"https://www.azlyrics.com/lyrics/megadeth/burn.html",
"https://www.azlyrics.com/lyrics/megadeth/builtforwar.html",
"https://www.azlyrics.com/lyrics/megadeth/offtheedge.html",
"https://www.azlyrics.com/lyrics/megadeth/danceintherain.html",
"https://www.azlyrics.com/lyrics/megadeth/thebeginningofsorrow.html",
"https://www.azlyrics.com/lyrics/megadeth/theblackestcrow.html",
"https://www.azlyrics.com/lyrics/megadeth/forgettoremember.html",
"https://www.azlyrics.com/lyrics/megadeth/dontturnyourback.html",
"https://www.azlyrics.com/lyrics/megadeth/coldsweat.html",

"https://www.azlyrics.com/lyrics/megadeth/thethreatisreal.html",
"https://www.azlyrics.com/lyrics/megadeth/dystopia.html",
"https://www.azlyrics.com/lyrics/megadeth/fatalillusion.html",
"https://www.azlyrics.com/lyrics/megadeth/deathfromwithin.html",
"https://www.azlyrics.com/lyrics/megadeth/bullettothebrain.html",
"https://www.azlyrics.com/lyrics/megadeth/postamericanworld.html",
"https://www.azlyrics.com/lyrics/megadeth/poisonousshadows.html",
"https://www.azlyrics.com/lyrics/pitbull/305anthem.html",
"https://www.azlyrics.com/lyrics/pitbull/culo.html",
"https://www.azlyrics.com/lyrics/pitbull/shesfreaky.html",
"https://www.azlyrics.com/lyrics/pitbull/shakeitup.html",
"https://www.azlyrics.com/lyrics/pitbull/toma.html",
"https://www.azlyrics.com/lyrics/pitbull/iwonder.html",
"https://www.azlyrics.com/lyrics/pitbull/getonthefloor.html",
"https://www.azlyrics.com/lyrics/pitbull/dirty.html",
"https://www.azlyrics.com/lyrics/pitbull/dammitman.html",
"https://www.azlyrics.com/lyrics/pitbull/wedontcareboutya.html",
"https://www.azlyrics.com/lyrics/pitbull/thatsnasty.html",
"https://www.azlyrics.com/lyrics/pitbull/backup.html",
"https://www.azlyrics.com/lyrics/pitbull/meltingpot.html",
"https://www.azlyrics.com/lyrics/pitbull/hustlerswithdrawal.html",
"https://www.azlyrics.com/lyrics/pitbull/hurryupandwait.html",
"https://www.azlyrics.com/lyrics/pitbull/culomiamimix.html",

"https://www.azlyrics.com/lyrics/pitbull/intro.html",
"https://www.azlyrics.com/lyrics/pitbull/miamishit.html",
"https://www.azlyrics.com/lyrics/pitbull/comeseeme.html",
"https://www.azlyrics.com/lyrics/pitbull/jealouso.html",
"https://www.azlyrics.com/lyrics/pitbull/qutsabesdeeso.html",
"https://www.azlyrics.com/lyrics/pitbull/bequiet.html",
"https://www.azlyrics.com/lyrics/pitbull/aychicolenguaafuera.html",
"https://www.azlyrics.com/lyrics/pitbull/fuego.html",
"https://www.azlyrics.com/lyrics/pitbull/amandadivaskit.html",
"https://www.azlyrics.com/lyrics/pitbull/bloodisthickerthanwater.html",
"https://www.azlyrics.com/lyrics/pitbull/junglefever.html",
"https://www.azlyrics.com/lyrics/pitbull/heyyougirl.html",
"https://www.azlyrics.com/lyrics/pitbull/raindrops.html",
"https://www.azlyrics.com/lyrics/pitbull/voodoo.html",
"https://www.azlyrics.com/lyrics/pitbull/descaradadance.html",
"https://www.azlyrics.com/lyrics/pitbull/dimeremix.html",
"https://www.azlyrics.com/lyrics/pitbull/bojangles.html",
"https://www.azlyrics.com/lyrics/pitbull/bornnraised.html",
"https://www.azlyrics.com/lyrics/pitbull/outro.html",

"https://www.azlyrics.com/lyrics/pitbull/alittlestoryintro.html",
"https://www.azlyrics.com/lyrics/pitbull/gogirl.html",
"https://www.azlyrics.com/lyrics/pitbull/dukeylove.html",
"https://www.azlyrics.com/lyrics/pitbull/midnight.html",
"https://www.azlyrics.com/lyrics/pitbull/yingtheyang.html",
"https://www.azlyrics.com/lyrics/pitbull/theanthem.html",
"https://www.azlyrics.com/lyrics/pitbull/thetruthinterlude.html",
"https://www.azlyrics.com/lyrics/pitbull/candyman.html",
"https://www.azlyrics.com/lyrics/pitbull/stickyicky.html",
"https://www.azlyrics.com/lyrics/pitbull/mylife.html",
"https://www.azlyrics.com/lyrics/pitbull/secretadmirer.html",
"https://www.azlyrics.com/lyrics/pitbull/getuplevantate.html",
"https://www.azlyrics.com/lyrics/pitbull/fuegodjbuddaremix.html",
"https://www.azlyrics.com/lyrics/pitbull/stripperpoleremix.html",
"https://www.azlyrics.com/lyrics/pitbull/unpoquito.html",
"https://www.azlyrics.com/lyrics/pitbull/tellmeremix.html",
"https://www.azlyrics.com/lyrics/pitbull/mr305outro.html",

"https://www.azlyrics.com/lyrics/pitbull/triumph.html",
"https://www.azlyrics.com/lyrics/pitbull/shutitdown.html",
"https://www.azlyrics.com/lyrics/pitbull/iknowyouwantmecalleocho.html",
"https://www.azlyrics.com/lyrics/pitbull/girls.html",
"https://www.azlyrics.com/lyrics/pitbull/fullofshit.html",
"https://www.azlyrics.com/lyrics/pitbull/dopeballinterlude.html",
"https://www.azlyrics.com/lyrics/pitbull/cantstopmenow.html",
"https://www.azlyrics.com/lyrics/pitbull/hotelroomservice.html",
"https://www.azlyrics.com/lyrics/pitbull/juicebox.html",
"https://www.azlyrics.com/lyrics/pitbull/callofthewild.html",
"https://www.azlyrics.com/lyrics/pitbull/krazy.html",
"https://www.azlyrics.com/lyrics/pitbull/givethemwhattheyaskfor.html",
"https://www.azlyrics.com/lyrics/pitbull/acrosstheworld.html",

"https://www.azlyrics.com/lyrics/pitbull/daddyslittlegirl.html",
"https://www.azlyrics.com/lyrics/pitbull/armandointro.html",
"https://www.azlyrics.com/lyrics/pitbull/malditoalcohol.html",
"https://www.azlyrics.com/lyrics/pitbull/estanoche.html",
"https://www.azlyrics.com/lyrics/pitbull/mujeres.html",
"https://www.azlyrics.com/lyrics/pitbull/bonbon.html",
"https://www.azlyrics.com/lyrics/pitbull/guantanamera.html",
"https://www.azlyrics.com/lyrics/pitbull/tucuerpo.html",
"https://www.azlyrics.com/lyrics/pitbull/vida23.html",
"https://www.azlyrics.com/lyrics/pitbull/amorosa.html",
"https://www.azlyrics.com/lyrics/pitbull/watagatapitusberry.html",
"https://www.azlyrics.com/lyrics/pitbull/orgullo.html",
"https://www.azlyrics.com/lyrics/pitbull/preguntale.html",

"https://www.azlyrics.com/lyrics/pitbull/mrworldwideintro.html",
"https://www.azlyrics.com/lyrics/pitbull/givemeeverything.html",
"https://www.azlyrics.com/lyrics/pitbull/rainoverme.html",
"https://www.azlyrics.com/lyrics/pitbull/heybabydropittothefloor.html",
"https://www.azlyrics.com/lyrics/pitbull/pause.html",
"https://www.azlyrics.com/lyrics/pitbull/comengo.html",
"https://www.azlyrics.com/lyrics/pitbull/shakeseora.html",
"https://www.azlyrics.com/lyrics/pitbull/internationallove.html",
"https://www.azlyrics.com/lyrics/pitbull/castlemadeofsand.html",
"https://www.azlyrics.com/lyrics/pitbull/tookmylove.html",
"https://www.azlyrics.com/lyrics/pitbull/wheredowego.html",
"https://www.azlyrics.com/lyrics/pitbull/somethingforthedjs.html",
"https://www.azlyrics.com/lyrics/pitbull/mrrightnow.html",
"https://www.azlyrics.com/lyrics/pitbull/shakeseoraremix.html",
"https://www.azlyrics.com/lyrics/pitbull/oyebaby.html",
"https://www.azlyrics.com/lyrics/pitbull/mykindagirl.html",

"https://www.azlyrics.com/lyrics/pitbull/globalwarmingintro.html",
"https://www.azlyrics.com/lyrics/pitbull/dontstoptheparty.html",
"https://www.azlyrics.com/lyrics/pitbull/feelthismoment.html",
"https://www.azlyrics.com/lyrics/pitbull/backintime.html",
"https://www.azlyrics.com/lyrics/pitbull/hopewemeetagain.html",
"https://www.azlyrics.com/lyrics/pitbull/partyaintover.html",
"https://www.azlyrics.com/lyrics/pitbull/drinksforyouladiesanthem.html",
"https://www.azlyrics.com/lyrics/pitbull/havesomefun.html",
"https://www.azlyrics.com/lyrics/pitbull/outtanowhere.html",
"https://www.azlyrics.com/lyrics/pitbull/tchutchutcha.html",
"https://www.azlyrics.com/lyrics/pitbull/lastnight.html",
"https://www.azlyrics.com/lyrics/pitbull/imoffthat.html",
"https://www.azlyrics.com/lyrics/pitbull/echapallamanosparriba.html",
"https://www.azlyrics.com/lyrics/pitbull/everybodyfucks.html",
"https://www.azlyrics.com/lyrics/pitbull/getitstarted.html",
"https://www.azlyrics.com/lyrics/pitbull/1159.html",

"https://www.azlyrics.com/lyrics/pitbull/timber.html",
"https://www.azlyrics.com/lyrics/pitbull/thathigh.html",
"https://www.azlyrics.com/lyrics/pitbull/doit.html",
"https://www.azlyrics.com/lyrics/pitbull/sunincalifornia.html",
"https://www.azlyrics.com/lyrics/pitbull/allthethings.html",

"https://www.azlyrics.com/lyrics/pitbull/ahleke.html",
"https://www.azlyrics.com/lyrics/pitbull/fun.html",
"https://www.azlyrics.com/lyrics/pitbull/fireball.html",
"https://www.azlyrics.com/lyrics/pitbull/timeofourlives.html",
"https://www.azlyrics.com/lyrics/pitbull/celebrate.html",
"https://www.azlyrics.com/lyrics/pitbull/sexybeaches.html",
"https://www.azlyrics.com/lyrics/pitbull/daydrinking.html",
"https://www.azlyrics.com/lyrics/pitbull/driveyoucrazy.html",
"https://www.azlyrics.com/lyrics/pitbull/wildwildlove.html",
"https://www.azlyrics.com/lyrics/pitbull/thisisnotadrill.html",
"https://www.azlyrics.com/lyrics/pitbull/weareoneoleola.html",

"https://www.azlyrics.com/lyrics/pitbull/piensasdilelaverdad.html",
"https://www.azlyrics.com/lyrics/pitbull/comoyoledoy.html",
"https://www.azlyrics.com/lyrics/pitbull/eltaxi.html",
"https://www.azlyrics.com/lyrics/pitbull/yoquierositteenamoras.html",
"https://www.azlyrics.com/lyrics/pitbull/elparty.html",
"https://www.azlyrics.com/lyrics/pitbull/mamimami.html",
"https://www.azlyrics.com/lyrics/pitbull/baddestgirlintown.html",
"https://www.azlyrics.com/lyrics/pitbull/chichibonbon.html",
"https://www.azlyrics.com/lyrics/pitbull/haciendoruido.html",
"https://www.azlyrics.com/lyrics/pitbull/hoysebebe.html",
"https://www.azlyrics.com/lyrics/pitbull/nopuedoms.html",
"https://www.azlyrics.com/lyrics/pitbull/queloque.html",

"https://www.azlyrics.com/lyrics/pitbull/wearestrong.html",
"https://www.azlyrics.com/lyrics/pitbull/badman.html",
"https://www.azlyrics.com/lyrics/pitbull/greenlight.html",
"https://www.azlyrics.com/lyrics/pitbull/messinaround.html",
"https://www.azlyrics.com/lyrics/pitbull/betteronme.html",
"https://www.azlyrics.com/lyrics/pitbull/sexybody.html",
"https://www.azlyrics.com/lyrics/pitbull/freedom.html",
"https://www.azlyrics.com/lyrics/pitbull/options.html",
"https://www.azlyrics.com/lyrics/pitbull/educateya.html",
"https://www.azlyrics.com/lyrics/pitbull/onlyonestoknow.html",
"https://www.azlyrics.com/lyrics/pitbull/dedicated.html",
"https://www.azlyrics.com/lyrics/pitbull/canthave.html",

"https://www.azlyrics.com/lyrics/pitbull/bojanglesremix.html",
"https://www.azlyrics.com/lyrics/pitbull/dammitmanremix.html",
"https://www.azlyrics.com/lyrics/pitbull/everybodygetup.html",
"https://www.azlyrics.com/lyrics/pitbull/freek.html",
"https://www.azlyrics.com/lyrics/pitbull/gettopoppinremix.html",
"https://www.azlyrics.com/lyrics/pitbull/jungle.html",
"https://www.azlyrics.com/lyrics/pitbull/latinosinparis.html",
"https://www.azlyrics.com/lyrics/pitbull/nastygirl.html",
"https://www.azlyrics.com/lyrics/pitbull/ohnohedidnt.html",
"https://www.azlyrics.com/lyrics/pitbull/partydance.html",
"https://www.azlyrics.com/lyrics/pitbull/pearlygates.html",
"https://www.azlyrics.com/lyrics/pitbull/porfavor.html",
"https://www.azlyrics.com/lyrics/pitbull/porfavorspanglishversion.html",
"https://www.azlyrics.com/lyrics/pitbull/subelasmanospaarriba.html",
"https://www.azlyrics.com/lyrics/pitbull/superstar.html",
"https://www.azlyrics.com/lyrics/pitbull/vacaciones.html",
"https://www.azlyrics.com/lyrics/pitbull/whooptwhoop.html",


};

    public static String[] getLyrics() throws MalformedURLException {
        Random rng = new Random();
        rng.setSeed(System.currentTimeMillis());
        return getRandomLines(getLyricsFromHTML(getURL(newURL(links[rng.nextInt(links.length)]))));
    }

    private static String getURL(URL url) {

        InputStream is = null;
        BufferedReader br;
        String page = "";

        try {
            is = url.openStream();  // throws an IOException
            br = new BufferedReader(new InputStreamReader(is));

            String line = "";
            while ((line = br.readLine()) != null) {
                page += line;
            }
        } catch (MalformedURLException mue) {
            mue.printStackTrace();
        } catch (IOException ioe) {
            ioe.printStackTrace();
            System.out.println(url);
        } finally {
            try {
                if (is != null) {
                    is.close();
                }
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }
        }
        return page;
    }

    private static String getLyricsFromHTML(String html) {
        String lyrics = "";
        int indexStart = html.indexOf("<!-- Usage of azlyrics.com content by any third-party lyrics provider is prohibited by our licensing agreement. Sorry about that. -->");
        int indexEnd = html.indexOf("<!-- MxM banner -->");
        String scraped = html.substring(indexStart + "<!-- Usage of azlyrics.com content by any third-party lyrics provider is prohibited by our licensing agreement. Sorry about that. -->".length(), indexEnd);
        scraped = scraped.replaceAll("<br>", "\n");
        scraped = scraped.replaceAll("</div>", "");
        scraped = scraped.replaceAll("<i>", "");
        scraped = scraped.replaceAll("</i>", "");
        scraped = scraped.replaceAll("<b>", "");
        scraped = scraped.replaceAll("</b>", "");
        scraped = scraped.trim();
        return scraped;
    }

    private static String[] getRandomLines(String lyrics) {

        String[] lines = lyrics.split("\n");
        ArrayList <String> list = new ArrayList<String>();
        for(String line : lines){
            if(line.length()!=0){
                list.add(line);
            }
        }

        Random rng = new Random();
        rng.setSeed(System.currentTimeMillis());
        int line = rng.nextInt(list.size() - 3);

        String[] returnedLines = new String[3];
        returnedLines[0] = list.get(line);
        returnedLines[1] = list.get(line+1);
        returnedLines[2] = list.get(line+2);
        return returnedLines;
    }
}
